{
 "title": "Beekeeper5 - beehive monitoring",
 "time": { "from": "now-10d", "to": "now-5d" },
 "panels": [
  {
   "title": "Weight delta forecasting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  pred_weight_delta,\n  actual_weight_delta\nFROM predictions\nORDER BY timestamp ASC",
     "rawQueryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  pred_weight_delta,\n  actual_weight_delta\nFROM predictions\nORDER BY timestamp ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Inside temperature forecasting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  pred_t_i_3,\n  actual_t_i_3\nFROM predictions\nORDER BY timestamp ASC",
     "rawQueryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  pred_t_i_3,\n  actual_t_i_3\nFROM predictions\nORDER BY timestamp ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Hive weight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  weight_kg\nFROM readings\nORDER BY timestamp ASC",
     "rawQueryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  weight_kg\nFROM readings\nORDER BY timestamp ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Inside temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  t\nFROM readings\nORDER BY timestamp ASC",
     "rawQueryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  t\nFROM readings\nORDER BY timestamp ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Outside temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  t_o\nFROM readings\nORDER BY timestamp ASC",
     "rawQueryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  t_o\nFROM readings\nORDER BY timestamp ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Inside humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  h\nFROM readings\nORDER BY timestamp ASC",
     "rawQueryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  h\nFROM readings\nORDER BY timestamp ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Atmosferic pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  p\nFROM readings\nORDER BY timestamp ASC",
     "rawQueryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  p\nFROM readings\nORDER BY timestamp ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}